name: On Demand Test

on:
  workflow_dispatch:
    inputs:
      test-tag:
        type: choice
        description: Select Test Tag
        options:
          - login
          - home
          - checkout
          - register-account
          - guest-account
          - currency
          - search
          - smoke
          - regression

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        containers: [1]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; f
      - name: Test with behave
        run: |
          behave features --tags=${{ github.event.inputs.test-tag }}